[platformio]
build_dir = .pio/build
libdeps_dir = .pio/libdeps

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps =
    adafruit/DHT sensor library @ ^1
    adafruit/Adafruit Unified Sensor @ ^1
monitor_speed = 115200
upload_speed = 115200
upload_flags = 
  --no-stub
  --before=no_reset
  --connect-attempts=20
upload_protocol = esptool
lib_ldf_mode = chain
