[platformio]
build_dir = .pio/build
libdeps_dir = .pio/libdeps

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    bblanchon/ArduinoJson @ ^6
monitor_speed = 115200
