[platformio]
build_dir = C:/.pio/build/smart-dacha-controller
libdeps_dir = C:/.pio/libdeps/smart-dacha-controller

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    bblanchon/ArduinoJson @ ^6
monitor_speed = 115200
